name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js and pnpm
      uses: pnpm/action-setup@v2
      with:
        node-version: 18
        version: 7  # Specify the version of pnpm you want to use

    - name: Install dependencies
      run: |
        pnpm install

    - name: Build
      run: |
        pnpm build

    - name: Test
      run: |
        pnpm test
