name: CI NestJs App

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Specify a valid Node.js version here
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Build and Test
        run: yarn build && yarn test
