name: Run NestJS App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js with pnpm
        uses: creepinson/pnpm-action@master
        with:
          node-version: 14

      - name: Install dependencies
        run: pnpm install

      - name: Build the app
        run: pnpm run build

  run-app:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Set up Node.js with pnpm
        uses: uses: creepinson/pnpm-action@master
        with:
          node-version: 14

      - name: Install dependencies
        run: pnpm install

      - name: Run the app
        run: pnpm run start:dev
