name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js with pnpm
        uses: pnpm/action-setup@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: pnpm install

      - name: Build the app
        run: pnpm run build
