name: Mirror to Bitbucket

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git credentials
        run: |
          echo "machine bitbucket.org login mina121-admin password \"$BITBUCKET_APP_PASSWORD\"" > ~/.netrc
          git config --global user.email "mina.sayed@exacall.com"
          git config --global user.name "Mina Sayed"

      - name: Debug 
        run: |
          git remote -v
          git branch -a
          git log --oneline -n 5

      - name: Mirror to Bitbucket
        run: |
          git remote add bitbucket https://mina121-admin@bitbucket.org/mina121/campgin_api.git
          git push --mirror bitbucket
        env:
          BITBUCKET_APP_PASSWORD: ${{ secrets.BITBUCKET_APP_PASSWORD }}
